# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Print version
        run: git describe --abbrev=0 --tags
    
      - uses: cardinalby/git-get-release-action@v1
        id: getrealease
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: '0.1' 
          
      - name: Print content
        run: echo {{ steps.getrealease.outputs.assets }}



  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
