# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
#      - name: Print version
#        run: git describe --abbrev=0 --tags
    
      - uses: cardinalby/git-get-release-action@v1
        id: getrealease
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: '0.1' 
          
      - name: Print content
        run: echo {{ steps.getrealease.outputs.assets }}
