name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
      pre_release:
        description: 'Is this a pre-release?'
        required: true
        default: 'true'
      draft:
        description: 'Draft?'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: gamejoltlibrary
          path: files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: filerelease
          path: releasefolder

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.version }}
          prerelease: true
          draft: true
          files: |
            releasefolder/*.txt
